version: "3"

services:
  vscode:
    container_name: vscode-live
    build: .
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      # - PASSWORD=admin
      - HASHED_PASSWORD=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918  # printf "admin" | sha256sum
      # - SUDO_PASSWORD=admin
      - SUDO_PASSWORD_HASH=$$6$$bnN^I9PyULi(]$$qW6h52NksF6sLfEbDGWK4V1RsLGkW460OYtawXXugRnBocLouAiaEFgEWQSs/J5HgA/VobEhr5msySOjfKRkY1 # openssl passwd -6 -salt $(tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13  ; echo) admin
    ports:
      - 8443:8443/tcp
    volumes:
      - ./config.yaml:/config/.config/code-server/config.yaml
      - ./vscode/home/:/home
    restart: unless-stopped
